name: Only update submodules (test)
on:
  workflow_dispatch:
  schedule:
    - cron: 0 */1 * * *
jobs:
  submodule:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
          submodules: recursive
      - name: Submodule update
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "noreply@github.com"
          mainRepo="ruddnev/itmo"
          headerPrefix="###"
          orgName=$(echo $mainRepo | tr -d "/")
          grep1="\(https:\/\/github\.com\/${orgName}\/[a-zA-Z0-9\-]{1,}(\/tree\/main)?\)"
          grep2="https:\/\/github\.com\/${orgName}\/[a-zA-Z0-9\-]{1,}$"
          curl -H 'Cache-Control: no-cache, no-store' -s https://raw.githubusercontent.com/${mainRepo}/main/README.md | grep -i -o -P "$grep1" | grep -o -P 's[0-9]-[a-zA-Z0-9]{1,}-[a-zA-Z0-9]{1,}' | sort > readmeRepos.tmp
          curl -H 'Cache-Control: no-cache, no-store' -s https://raw.githubusercontent.com/${mainRepo}/main/.gitmodules | grep -i -o -P "$grep2" | grep -o -P 's[0-9]-[a-zA-Z0-9]{1,}-[a-zA-Z0-9]{1,}' | sort > submoduleRepos.tmp
          touch newLastCommits.tmp
          cat submoduleRepos.tmp | while read repoName; do if [ -z "$repoName" ]; then echo line is empty!; else result=$(curl -s -H "Accept: application/vnd.github.VERSION.sha" "https://api.github.com/repos/${orgName}/${repoName}/commits/main"); echo "${repoName}: ${result}" >> newLastCommits.tmp; fi; done; 
          sort -o sortedNewLastCommits.tmp newLastCommits.tmp; rm newLastCommits.tmp
          newLastCommits="sortedNewLastCommits.tmp"
          lastCommits=".github/workflows/lastCommits.txt"
          if [ -f "$lastCommits" ]; then if cmp --silent -- "$lastCommits" "$newLastCommits"; then echo "no changes"; else git submodule update --recursive --remote; git commit -am "making submodules keep track of main branch"; fi; else cp $newLastCommits $lastCommits; git add $lastCommits; git commit -m "making first copy of lastCommits"; fi
          git push
